# # -*- coding: utf-8 -*-
# # Generated by Django 1.9.6 on 2016-05-05 03:17
# from __future__ import unicode_literals
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#     ]
#
#     operations = [
#     ]


# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 03:17
from __future__ import unicode_literals

from django.db import migrations

def get_movies(apps, schema_editor):

    Movie = apps.get_model("ratings", "Movie")
    for movie in Movie.objects.all():
        movie.name = "%s %s" % (movie.user_id, movie.movie_id, movie.rating)
        movie.save()

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_movies),
    ]
