# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:44
from __future__ import unicode_literals

from django.db import migrations
import csv


def get_rater(apps, schema_editor):
    Rater = apps.get_model("ratings", "Rater")
    with open('../ml-100k/u.user', 'r') as f:
        data = csv.reader(f, delimiter='|')
        for row in data:
            rater = Rater(age=row[1], gender=row[2])
            rater.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_rater),
    ]
