# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 20:44
from __future__ import unicode_literals

from django.db import migrations
import csv
from datetime import date, datetime


def get_movie(apps, schema_editor):
    Movie = apps.get_model("ratings", "Movie")
    with open('../ml-100k/u.item', encoding='latin_1') as f:
        data = csv.reader(f, delimiter='|')
        for row in data:
            release = row[2]
            if release:
                release = datetime.strptime(release, '%d-%b-%Y').date()
            else:
                release = date(1, 1, 1)

            movie = Movie(id=row[0], title=row[1], release_date=release)
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20160505_2044'),
    ]

    operations = [
        migrations.RunPython(get_movie),
    ]
