# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


def set_user_info(apps, schema_editor):
    Rater = apps.get_model("ratings", "Rater")
    for rater in Rater.objects.all():
        user = User(username='stacy' + str(rater.id), email='email' + str(rater.id) + '@gmail.com', password='password')
        user.save()
        rater.user_id = user
        rater.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0006_auto_20160507_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(set_user_info),
    ]
